import {pool,initDb} from "./db";import {enc,dec} from "./crypto";
const ACCOUNT="https://account.accurate.id";
export type Role="source"|"target";
async function token(role:Role){await initDb();const r=await pool.query("select * from oauth_connections where role=$1 order by updated_at desc limit 1",[role]);if(!r.rowCount) throw new Error(`${role} belum terhubung OAuth`);let x=r.rows[0];if(x.expires_at && new Date(x.expires_at).getTime()<Date.now()+86400000 && x.refresh_token){const basic=Buffer.from(`${process.env.AOL_CLIENT_ID}:${process.env.AOL_CLIENT_SECRET}`).toString("base64");const body=new URLSearchParams({grant_type:"refresh_token",refresh_token:dec(x.refresh_token)});const z=await fetch(`${ACCOUNT}/oauth/token`,{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/x-www-form-urlencoded"},body});if(!z.ok) throw new Error(`Refresh OAuth gagal ${z.status}`);const j=await z.json();await pool.query("update oauth_connections set access_token=$1,refresh_token=$2,expires_at=now()+($3||' seconds')::interval,scope=$4,updated_at=now() where id=$5",[enc(j.access_token),enc(j.refresh_token||dec(x.refresh_token)),j.expires_in,j.scope,x.id]);x=(await pool.query("select * from oauth_connections where id=$1",[x.id])).rows[0]}return {id:x.id,accessToken:dec(x.access_token)}}
export function authorizeUrl(role:Role,state:string){const q=new URLSearchParams({client_id:process.env.AOL_CLIENT_ID!,response_type:"code",redirect_uri:process.env.AOL_REDIRECT_URI!,scope:process.env.AOL_SCOPES||"journal_voucher_view journal_voucher_save sales_invoice_view sales_invoice_save sales_receipt_view sales_receipt_save purchase_invoice_view purchase_invoice_save purchase_payment_view purchase_payment_save other_payment_view other_payment_save other_deposit_view other_deposit_save glaccount_view glaccount_save item_view item_save customer_view customer_save vendor_view vendor_save fixed_asset_view",state:`${role}:${state}`});return `${ACCOUNT}/oauth/authorize?${q}`}
export async function exchangeCode(role:Role,code:string){await initDb();const basic=Buffer.from(`${process.env.AOL_CLIENT_ID}:${process.env.AOL_CLIENT_SECRET}`).toString("base64");const body=new URLSearchParams({code,grant_type:"authorization_code",redirect_uri:process.env.AOL_REDIRECT_URI!});const r=await fetch(`${ACCOUNT}/oauth/token`,{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/x-www-form-urlencoded"},body});if(!r.ok) throw new Error(`OAuth token gagal ${r.status}: ${await r.text()}`);const j=await r.json();const id=crypto.randomUUID();await pool.query("delete from oauth_connections where role=$1",[role]);await pool.query("insert into oauth_connections(id,role,access_token,refresh_token,expires_at,scope) values($1,$2,$3,$4,now()+($5||' seconds')::interval,$6)",[id,role,enc(j.access_token),j.refresh_token?enc(j.refresh_token):null,j.expires_in,j.scope]);return id}
export async function dbList(role:Role){const t=await token(role);const r=await fetch(`${ACCOUNT}/api/db-list.do`,{headers:{Authorization:`Bearer ${t.accessToken}`}});if(!r.ok)throw new Error(`db-list ${r.status}`);return r.json()}
export async function selectDb(role:Role,id:number,alias:string){const t=await token(role);const r=await fetch(`${ACCOUNT}/api/open-db.do?id=${id}`,{headers:{Authorization:`Bearer ${t.accessToken}`},redirect:"follow"});if(!r.ok)throw new Error(`open-db ${r.status}`);const j=await r.json();await initDb();await pool.query(`insert into selected_databases(role,connection_id,database_id,alias,host,session_id) values($1,$2,$3,$4,$5,$6) on conflict(role) do update set connection_id=excluded.connection_id,database_id=excluded.database_id,alias=excluded.alias,host=excluded.host,session_id=excluded.session_id,updated_at=now()`,[role,t.id,id,alias,j.host,j.session]);return j}
export async function context(role:Role){await initDb();const d=await pool.query("select * from selected_databases where role=$1",[role]);if(!d.rowCount)throw new Error(`${role} database belum dipilih`);const t=await token(role);let x=d.rows[0];const r=await fetch(`${ACCOUNT}/api/open-db.do?id=${x.database_id}`,{headers:{Authorization:`Bearer ${t.accessToken}`},redirect:"follow"});if(r.ok){const j=await r.json();x={...x,host:j.host,session_id:j.session};await pool.query("update selected_databases set host=$1,session_id=$2,updated_at=now() where role=$3",[j.host,j.session,role])}return {...x,accessToken:t.accessToken}}
export async function accurateGet(role:Role,path:string,params:Record<string,string>){const c=await context(role);const u=new URL(`${c.host}/accurate${path}`);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{headers:{Authorization:`Bearer ${c.accessToken}`,"X-Session-ID":c.session_id},redirect:"follow"});const txt=await r.text();let j;try{j=JSON.parse(txt)}catch{throw new Error(`AOL ${r.status}: ${txt.slice(0,300)}`)}if(!r.ok||j.s===false)throw new Error(j.d?.join?.("; ")||`AOL ${r.status}`);return j}
export async function accuratePost(role:Role,path:string,body:URLSearchParams){const c=await context(role);const r=await fetch(`${c.host}/accurate${path}`,{method:"POST",headers:{Authorization:`Bearer ${c.accessToken}`,"X-Session-ID":c.session_id,"Content-Type":"application/x-www-form-urlencoded"},body,redirect:"follow"});const txt=await r.text();let j;try{j=JSON.parse(txt)}catch{throw new Error(`AOL ${r.status}: ${txt.slice(0,300)}`)}if(!r.ok||j.s===false)throw new Error(j.d?.join?.("; ")||`AOL ${r.status}`);return j}
